openapi: "3.0.2"
info:
  title: unibox API"
  version: "2.0.0"
servers:
  - url: "http://localhost:8080"
  - url: "http://localhost:3000"
paths:
  /users:
    get:
      tags:
        - user
      summary: "全ユーザーを取得"
      responses:
        "200":
          description: "ユーザーリストの取得に成功しました"
  /signin:
    post:
      summary: Sign in to the application
      description: Allows users to sign in using their email and password.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                  description: User's email
                  example: user@example.com
                password:
                  type: string
                  description: User's password
                  example: "yourpassword"
              required:
                - email
                - password
      responses:
        "200":
          description: Successful sign in
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    description: Access token for the authenticated session
                  user:
                    type: object
                    properties:
                      id:
                        type: integer
                        format: int64
                        description: User's unique identifier
                      name:
                        type: string
                        description: User's full name
              example:
                token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
                user:
                  id: 123
                  name: John Doe
        "400":
          description: Invalid request parameters
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Description of the input error
                    example: "invalid request parameters"
        "401":
          description: Unauthorized - Incorrect email or password
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Explanation of the error
                    example: "failed to sign in"
  /signUp:
    post:
      tags:
        - user
      summary: "新規登録"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: "新規登録に成功しました"
        "400":
          description: "新規登録に失敗しました"
