openapi: "3.0.2"
info:
  title: unibox API"
  version: "2.0.0"
servers:
  - url: "http://localhost:8080"
  - url: "http://localhost:3000"
paths:
  /users:
    get:
      tags:
        - user
      summary: "全ユーザーを取得"
      responses:
        "200":
          description: "ユーザーリストの取得に成功しました"
  /signIn:
    post:
      tags:
        - user
      summary: "ログイン"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: "ログインに成功しました"
        "400":
          description: "ログインに失敗しました"
  /signUp:
    post:
      tags:
        - user
      summary: "新規登録"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: "新規登録に成功しました"
        "400":
          description: "新規登録に失敗しました"
